### ISSUE TITLE
set-output command is deprecated

### ISSUE THREAD

**Issue by thekevinscott** [maybe-hello-world/pyproject-check-version#4]
In my CI output, I'm seeing the following warning:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

On the [linked blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) they write:

> 24-July-2023 Update: Our telemetry shows significant usage of these commands so we have decided to postpone the removal. To learn more, visit the [latest changelog post](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).

So I'm not sure that there's any impending deprecation, but it certainly seems like the intent is to encourage folks to migrate away from `set-output`.

**Comment by maybe-hello-world** [comment]
Hmm, what version of the action you're using?
The last ones (v3 and v4) use the $GITHUB_OUTPUT file so you shouldn't see the warning. I'll double-check.

**Comment by thekevinscott** [comment]
That was the problem - upgrading to v4 was the solution. Thank you!
